### PR TITLE
bootstrapping style guides

### PR DESCRIPTION
**Pull request by amitschang**
Adding style configs for java and python. 

* Python is pretty trivial to read, since all we do is update line length from default.
* for java: 
  * updated indentation from defaults in these lines: https://github.com/sciserver/sciserver-guidelines/blob/initialize/coding-style/java/checkstyle.xml#L248-L255
  * updated line length at: https://github.com/sciserver/sciserver-guidelines/blob/initialize/coding-style/java/checkstyle.xml#L50

### CODE REVIEW

**Review by dmedv — APPROVED** [review]

**Review by shandy79 — APPROVED** [review]
Should we add in a subsequent commit matching style files for IDEs?

**Comment by amitschang** [comment]
> Should we add in a subsequent commit matching style files for IDEs?

Yes, should definitely do that.

**Comment by glemson** [comment]
good, then I will also approve

**Review by glemson — APPROVED** [review]

**Comment by amitschang** [comment]
Great! I will merge this in as-is to kick it off. If anyone already has those IDE style files, please feel free to add. You can check eveything works by adding the checkstyle stuff to build.grade as in the readmes.

**Pull request merged**
